# agents/coder.py
"""
Coder Agent — Part 3
Takes the Planner Agent's roadmap + original legacy source and
prompts the LLM to generate converted Python 3 code, then wraps
it as a minimal FastAPI microservice.
"""

import json
import os
import re
import ollama

from agents.planner import generate_roadmap, MODEL_NAME


def build_conversion_prompt(legacy_source: str, roadmap: dict) -> str:
    """Builds a prompt instructing the LLM to convert legacy code to Python 3."""
    steps_text = "\n".join(f"- {step}" for step in roadmap.get("conversion_steps", []))

    prompt = f"""You are a senior Python engineer. Convert the following legacy Python 2 code to clean, modern Python 3.

ORIGINAL LEGACY CODE:
```python
{legacy_source}
```

REQUIRED CONVERSION STEPS (from the modernization roadmap):
{steps_text}

RULES:
- Output ONLY the converted Python 3 code.
- Wrap your entire response in a single ```python code fence — nothing before or after it.
- Preserve all original function and class names exactly (do not rename them).
- Preserve the original logic and behavior — do not add new features.
- Use f-strings instead of %-style formatting.
- Add type hints to function signatures.
- Add a short docstring to each function and class.
"""
    return prompt


def call_llm_for_code(prompt: str) -> str:
    response = ollama.chat(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        options={"temperature": 0.1},  # even lower temp — code needs to be precise, not creative
    )
    return response["message"]["content"]


def extract_code_from_response(raw_text: str) -> str:
    """
    Pulls code out of a ```python ... ``` fence.
    Falls back to returning the raw text if no fence is found
    (in case the model ignores the formatting instruction).
    """
    match = re.search(r"```python\s*\n(.*?)```", raw_text, re.DOTALL)
    if match:
        return match.group(1).strip()

    match = re.search(r"```\s*\n(.*?)```", raw_text, re.DOTALL)
    if match:
        return match.group(1).strip()

    # No fence found at all — return as-is and let the caller decide
    return raw_text.strip()


def convert_legacy_code(filepath: str, roadmap: dict) -> str:
    """Converts a legacy file to Python 3 based on the roadmap."""
    with open(filepath, "r", encoding="utf-8") as f:
        legacy_source = f.read()

    prompt = build_conversion_prompt(legacy_source, roadmap)
    raw_response = call_llm_for_code(prompt)
    converted_code = extract_code_from_response(raw_response)
    return converted_code


def wrap_as_fastapi_service(converted_code: str, service_name: str) -> str:
    """
    Wraps converted code as a minimal FastAPI service.
    For this step, we keep it simple: expose ONE endpoint that
    runs the main report-generating logic and returns its result.
    We'll make this smarter (auto-detecting routes) in a later step.
    """
    api_wrapper = f'''"""
Auto-generated FastAPI service for: {service_name}
Generated by Coder Agent - do not edit manually, re-run pipeline instead.
"""

from fastapi import FastAPI
import io
import contextlib

app = FastAPI(title="{service_name}")

# ---- Converted legacy logic below ----

{converted_code}

# ---- Auto-generated API route ----

@app.get("/run")
def run_service():
    """Runs the converted logic and captures printed output."""
    buffer = io.StringIO()
    try:
        with contextlib.redirect_stdout(buffer):
            inventory = load_inventory()
            print_report(inventory)
        return {{"status": "success", "output": buffer.getvalue()}}
    except Exception as e:
        return {{"status": "error", "message": str(e)}}


@app.get("/")
def root():
    return {{"service": "{service_name}", "status": "running"}}
'''
    return api_wrapper


def save_service(service_code: str, service_name: str):
    """Saves the generated FastAPI service to /generated/<service_name>/main.py"""
    output_dir = os.path.join("generated", service_name)
    os.makedirs(output_dir, exist_ok=True)

    filepath = os.path.join(output_dir, "main.py")
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(service_code)

    req_path = os.path.join(output_dir, "requirements.txt")
    with open(req_path, "w", encoding="utf-8") as f:
        f.write("fastapi\nuvicorn\n")

    # Permanent Dockerfile so CI/CD (GitHub Actions) can build this
    # service directly, independent of the local sandbox test runner.
    dockerfile_path = os.path.join(output_dir, "Dockerfile")
    dockerfile_content = """FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
"""
    with open(dockerfile_path, "w", encoding="utf-8") as f:
        f.write(dockerfile_content)

    print(f"✅ Saved generated service to: {filepath}")
    return filepath

if __name__ == "__main__":
    LEGACY_FILE = "legacy_samples/inventory.py"
    SERVICE_NAME = "inventory_service"

    print("Step 1/3: Generating roadmap...")
    roadmap = generate_roadmap(LEGACY_FILE)
    print(json.dumps(roadmap, indent=2))

    print("\nStep 2/3: Converting legacy code to Python 3...")
    converted = convert_legacy_code(LEGACY_FILE, roadmap)
    print("\n--- Converted Code Preview ---\n")
    print(converted)

    print("\nStep 3/3: Wrapping as FastAPI service...")
    service_code = wrap_as_fastapi_service(converted, SERVICE_NAME)
    save_service(service_code, SERVICE_NAME)